[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
rust-fsm = "0.8"ge]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
