name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    
    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install trunk and wasm-bindgen-cli
      run: |
        cargo install trunk wasm-bindgen-cli
    
    - name: Run tests
      run: cargo test --all-features
    
    - name: Check formatting
      run: cargo fmt -- --check
    
    - name: Run clippy
      run: cargo clippy -- -D warnings
    
    - name: Build web client
      run: |
        cd web
        trunk build --release
    
    - name: Build server
      run: cargo build --release --bin server

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: docker build -t rracer:latest .
    
    - name: Test Docker image
      run: |
        docker run -d -p 3000:3000 --name rracer-test rracer:latest
        sleep 10
        curl -f http://localhost:3000 || exit 1
        docker stop rracer-test
